### ISSUE TITLE
FES Driver only inputs first two DVPs

### ISSUE THREAD

**Issue by cavery12** [charlesdavid/JED#3]
When I am using the FES_Driver.jar file, no matter which DVPs I use the program only shows the first two. I am using files from the most recent update form this Github account.

**Comment by charlesdavid** [comment]
Hi Chris, I have just created a Jupyter Notebook to test some of the JED drivers, including FES. I have not been able to reproduce the error you describe. I know that this was an issue in Singam's older version, but not with the new jars. Here is the test data for FES: https://github.com/charlesdavid/JED/tree/master/test/Single/JED_RESULTS_TEST_SINGLE/cPCA/CORR/FES  The most recent test data shows that OP1 and OP2 can be set. Can you please verify that you are using a correct input file? There are a number of sample input files in https://github.com/charlesdavid/JED/tree/master/input_files Thanks for your interest in JED.

**Comment by cavery12** [comment]
I have now been able to get the FES driver to assign the OP1 and OP2. I rewrote my input file again based on the ones you linked me too so the issue must have been there. The driver seems to be working fine now, thank you for your help!

**Comment by charlesdavid** [comment]
You are very welcome @cavery12 . FYI, there is no need to construct input files _ab-initio_ as they are provided as part of the JED package. It was hoped that users would only need to _edit_ the files for their particular needs/environments, thereby lowering the "learning curve" of the software. I will continue to develop these input files, and am currently releasing more 'versions'... recall that you can pass the `path/name` of your custom input files to the drivers. Cheers!
